### ISSUE TITLE
Docs about differences between Emgo and Go?

### ISSUE THREAD

**Issue by bkaradzic** [ziutek/emgo#3]
I just noticed this project, it looks cool, but documentation is a little bit sparse.

Is there one page summary about differences between Emgo and Go?

**Comment by ziutek** [comment]
Please read doc/spec.txt

**Comment by bkaradzic** [comment]
:+1: Ah cool, didn't see it linked elsewhere, but totally missed it when I was browsing repo. If you rename files to .md GitHub will automatically format it with markdown.

**Comment by ziutek** [comment]
You are right.Fixed.
